[book]
title = "The Complete Future Trait Guide"
description = "Mastering Async Programming in Rust"
authors = ["Hamze Ghalebi"]
language = "en"
multilingual = false
src = "book"

[rust]
edition = "2021"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
no-section-label = false
git-repository-url = "https://github.com/your-repo/future-trait-tutorial"
edit-url-template = "https://github.com/your-repo/future-trait-tutorial/edit/main/book/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0

[output.epub]
# EPUB-specific configuration
cover-image = "theme/cover.png"
additional-css = ["theme/epub.css"]
use-default-css = true
curly-quotes = true

[preprocessor.links]
# Custom link preprocessing if needed

[preprocessor.index]
# Custom index preprocessing if needed
